# .github/ISSUE_TEMPLATE/bug_report.yml
name: "🚫 Bug Report"
description: Report a bug or unexpected behavior
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out this form so we can help you faster.
  - type: input
    id: what-happened
    attributes:
      label: What happened?
      placeholder: Describe the bug in one sentence
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: List the steps to recreate the issue
  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: OS, Browser, Version, etc.
