name: "\u2728 Feature Request"
description: Suggest an idea for this project
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your suggestion! Please complete the following to help us understand your idea.
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      placeholder: What would you like to see added?
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      placeholder: How would this feature help users?
